# Generated by Django 6.0.3 on 2026-04-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, verbose_name='Cihaz Kimliği')),
                ('temperature', models.FloatField(verbose_name='Sıcaklık (°C)')),
                ('humidity', models.FloatField(verbose_name='Hava Nemi (%)')),
                ('soil_moisture', models.FloatField(verbose_name='Toprak Nemi (%)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Zamanı')),
            ],
            options={
                'verbose_name_plural': 'Sensör Verileri',
            },
        ),
    ]
